class Language():
    def setARABIC(self):
        self.CAMERA = 'كاميرة'
        self.FACENOTRECOGNIZED = 'الوجه غير معروف'
        self.CLEAR = 'واضح'
        self.FACERECOGNIZED = 'التعرف على الوجه'
        self.ADDUSBCAMERA = "أضف كاميرة USB"
        self.ADDIPCAMERA = "أضف كاميرة IP"
        self.TRAIN = "تدريب"
        self.VIEWATTENDANCE ='عرض الحضور'
        self.LOGOUT = "تسجيل خروج"
        self.PURGE = "تطهير"
        self.ATTENDANCE = "الحضور"
        self.CLOSE = "إلغاء"
        self.DATE = "تاريخ"
        self.TIME = "وقت"
        self.NAME = "اسم"
        self.NO = 'لا'
        self.YES = 'نعم'
        self.QUESTIONPURGE ='هل أنت متأكد أنك تريد إزالة جميع البيانات'
        self.CLICKTOSTARTTRAINING ='انقر فوق تدريب لبدء التدريب'
        self.HALTEDNOTENOUGHDATA = 'تم إيقاف البيانات غير كافية'
        self.NOTENOUGHDATAFORTRAINING = 'لا توجد بيانات كافية للتدريب'
        self.DELETE ='حذف'
        self.VIEWALLTIME ='عرض الحضور'
        self.ADD ='أضف'
        self.ADDTODATABASE = 'إضافة إلى قاعدة البيانات'
        self.UNRECOGNIZED = 'غير مسجل'
        self.RECOGNIZED = 'Recognized'
        self.VIEW ='عرض'
        self.ENTERIPSOURCE ='أضف كاميرة IP'
        self.CANCEL = 'إلغاء'
        # self.name = 
    def setENGLISH(self):
        self.CAMERA = 'Camera'
        self.FACENOTRECOGNIZED = 'FACE NOT RECOGNIZED'
        self.CLEAR = 'clear'
        self.FACERECOGNIZED = 'FACE RECOGNIZED'
        self.ADDUSBCAMERA = "Add USB Camera"
        self.ADDIPCAMERA = "Add IP Camera"
        self.TRAIN ='Train'
        self.VIEWATTENDANCE = 'View Attendance'
        self.LOGOUT ='Logout'
        self.PURGE = 'PURGE'
        self.ATTENDANCE = "Attendance"
        self.CLOSE = "Close"
        self.DATE = "Date"
        self.TIME = "Time"
        self.NAME = "Name"
        self.NO ="No"
        self.YES = "Yes"
        self.QUESTIONPURGE = 'Are You Sure you want to purge/remove all data'
        self.CLICKTOSTARTTRAINING ="Click Train To Start Training"
        self.HALTEDNOTENOUGHDATA = 'HALTED Not Enough Data'
        self.NOTENOUGHDATAFORTRAINING ='Not enough data For Training'
        self.DELETE ='Delete'
        self.VIEWALLTIME = 'View All Time'
        self.ADD ="Add"
        self.ADDTODATABASE = "Add To Database"
        self.UNRECOGNIZED = 'UnRecognized'
        self.RECOGNIZED = 'UnRecognized'
        self.VIEW ='View'
        self.ENTERIPSOURCE ='Eenter IP Source'
        self.CANCEL = 'Cancel'